<?php
// fetch_students_by_department.php

// Include your database connection file
include 'db2_connect.php';
require_once 'TCPDF-main/tcpdf.php';

session_start();
$generatedBy = $_SESSION['name'] ?? 'System'; // Get logged-in user's name

// Retrieve parameters from the GET request
$school = $_GET['school'] ?? '';
$department = $_GET['department'] ?? '';
$startDate = $_GET['start_date'] ?? '';
$endDate = $_GET['end_date'] ?? '';

// Basic input validation
if (empty($school) || empty($department) || empty($startDate) || empty($endDate)) {
    die("Missing parameters. Please provide school, department, start date, and end date.");
}

// SQL query to fetch students based on school, department, and registration date
$sql = "SELECT Student_ID, Name, Email, Contact_No, school, department, Course
        FROM students
        WHERE school = ? AND department = ? AND Registration_Date BETWEEN ? AND ?";

$stmt = $conn->prepare($sql);

if (!$stmt) {
    die("Database error: " . $conn->error);
}

$stmt->bind_param("ssss", $school, $department, $startDate, $endDate);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows === 0) {
    die("No students found for the given criteria.");
}

// Custom TCPDF class with header and footer
class CustomPDF extends TCPDF {
    protected $generatedBy;
    protected $showFirstPageHeader = true;

    public function setGeneratedBy($name) {
        $this->generatedBy = $name;
    }

    public function setShowFirstPageHeader($show = true) {
        $this->showFirstPageHeader = $show;
    }

    public function Header() {
        if ($this->PageNo() == 1 && $this->showFirstPageHeader) {
            // Logo
            $this->Image('Ku_logo.jpeg', 15, 10, 25, 25, 'JPEG');
            // University Name
            $this->SetFont('Helvetica', 'B', 16);
            $this->Cell(0, 10, 'Kenyatta University', 0, 1, 'C');
            // System Name
            $this->SetFont('Helvetica', 'B', 14);
            $this->Cell(0, 10, 'Student Lecturer Appointment System', 0, 1, 'C');
            $this->Ln(5);
            // "Generated By" information
            $this->SetFont('Helvetica', 'I', 10);
            $this->Cell(0, 10, 'Generated By: ' . $this->generatedBy, 0, 1, 'R');
            $this->Ln(10); // Add some space after the header
        }
    }

    public function Footer() {
        $this->SetY(-25);
        $this->SetFont('Helvetica', 'I', 9);
        $this->Cell(0, 10, '________________________________________________', 0, 1, 'C');
        $this->SetFont('Helvetica', 'B', 10);
        $this->Cell(0, 10, 'Kenyatta University Student Lecturer Appointment System', 0, 1, 'C');
        $this->Ln(3);
        $this->SetFont('Helvetica', 'I', 9);
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage() . ' of ' . $this->getAliasNbPages(), 0, 1, 'C');
    }
}

// Create a new PDF document
$pdf = new CustomPDF();
$pdf->setGeneratedBy($generatedBy);
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 30);
$pdf->AddPage();
$pdf->SetFont('Helvetica', '', 12);

// Report Title
$pdf->SetFont('Helvetica', 'B', 16);
$pdf->Cell(0, 10, "Registered Students Report", 0, 1, 'C');
$pdf->Ln(3);

// Date Range (Centered)
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(0, 10, "From: $startDate To: $endDate", 0, 1, 'C');
$pdf->Ln(5);

// School and Department (Left-aligned)
$pdf->SetFont('Helvetica', '', 12);
$pdf->Cell(0, 8, "School: $school", 0, 1, 'L');
$pdf->Cell(0, 8, "Department: $department", 0, 1, 'L');
$pdf->Ln(10);

// Table Headers
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->SetFillColor(230, 230, 230);
$pdf->SetTextColor(0);
$pdf->SetDrawColor(128, 128, 128);
$pdf->SetLineWidth(0.3);
$header = ['STUDENT ID', 'Name', 'Email', 'Contact No.', 'Course'];
$columnWidths = [30, 40, 50, 30, 40, 35];
for ($i = 0; $i < count($header); $i++) {
    $pdf->Cell($columnWidths[$i], 10, $header[$i], 1, 0, 'C', true);
}
$pdf->Ln();

// Table Data
$pdf->SetFont('Helvetica', '', 10);
$pdf->SetFillColor(245, 245, 245);
$pdf->SetTextColor(0);
$fill = false;
while ($row = $result->fetch_assoc()) {
    $pdf->Cell($columnWidths[0], 8, $row['Student_ID'], 'LR', 0, 'C', $fill);
    $pdf->Cell($columnWidths[1], 8, $row['Name'], 'LR', 0, 'L', $fill);
    $pdf->Cell($columnWidths[2], 8, $row['Email'], 'LR', 0, 'L', $fill);
    $pdf->Cell($columnWidths[3], 8, $row['Contact_No'], 'LR', 0, 'C', $fill);
    $pdf->Cell($columnWidths[4], 8, $row['Course'], 'LR', 0, 'C', $fill);
    $pdf->Ln();
    $fill = !$fill;
}
// Closing the table border
for ($i = 0; $i < count($header); $i++) {
    $pdf->Cell($columnWidths[$i], 0, '', 'T');
}
$pdf->Ln();

// Output the PDF
$pdf->Output('students_report.pdf', 'I');

$stmt->close();
$conn->close();
?>